/*
    ShiftDesk - database setup
    CSC 2210 Object Oriented Programming 2 (C#), Lab 1 Resubmission
    Student ID 21-45717-3

    Run this once in SQL Server Management Studio, or in the SQL Server Object
    Explorer inside Visual Studio, before starting the application.

    Running it a second time is harmless. Every step checks whether the thing it
    creates is already there, so re-running will not throw and will not delete
    accounts registered while testing. There is a deliberate reset at the very
    bottom that has to be selected and run on its own.
*/


-- The database --------------------------------------------------------------

IF DB_ID('db_users') IS NULL
    CREATE DATABASE db_users;
GO

USE db_users;
GO


-- The table -----------------------------------------------------------------
--
--   id        Generated by SQL Server. IDENTITY(1,1) starts at 1 and adds 1
--             each time, so the application never has to work out the next
--             number, and two people registering at once cannot collide.
--
--   username  UNIQUE. The registration form checks for a duplicate first so it
--             can show a sentence rather than an error, but this constraint is
--             what actually makes it impossible.
--
--   password  Never the password. This column holds the SHA-256 digest of the
--             password, written as 64 hexadecimal characters. The CHECK below
--             enforces that length, so a plain-text password cannot be dropped
--             into this table by hand without SQL Server rejecting it.

IF OBJECT_ID('dbo.tbl_users', 'U') IS NULL
    CREATE TABLE tbl_users (
        id       INT IDENTITY(1,1) PRIMARY KEY,
        username NVARCHAR(50)  NOT NULL UNIQUE,
        password NVARCHAR(100) NOT NULL CHECK (LEN(password) = 64)
    );
GO


-- The test account ----------------------------------------------------------
--
--   username  admin
--   password  admin123
--
-- The value stored is not the word admin123. It is SHA-256 of admin123. The
-- application hashes whatever is typed into the password box and compares the
-- two digests, so the readable password exists nowhere in the database.

IF NOT EXISTS (SELECT 1 FROM tbl_users WHERE username = 'admin')
    INSERT INTO tbl_users (username, password)
    VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9');
GO


-- Checks --------------------------------------------------------------------
--
-- The first query is the one to run on camera, before and after registering.
-- The second proves the stored value really is SHA-256 of admin123 by having
-- SQL Server work the digest out itself and putting the two side by side.

SELECT id, username, password FROM tbl_users;
GO

SELECT  username,
        password                                                     AS stored_hash,
        LOWER(CONVERT(NVARCHAR(100), HASHBYTES('SHA2_256', 'admin123'), 2))
                                                                     AS recomputed_hash
FROM    tbl_users
WHERE   username = 'admin';
GO


/*
    Reset - nothing below this line runs unless it is selected and executed
    on its own.

    Wipes every account and puts the table back to just admin. Handy right
    before recording, so the account registered on camera is obviously new.

        DROP TABLE tbl_users;

        CREATE TABLE tbl_users (
            id       INT IDENTITY(1,1) PRIMARY KEY,
            username NVARCHAR(50)  NOT NULL UNIQUE,
            password NVARCHAR(100) NOT NULL CHECK (LEN(password) = 64)
        );

        INSERT INTO tbl_users (username, password)
        VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9');
*/
